package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consultorios generated by hbm2java
 */
public class Consultorios  implements java.io.Serializable {


     private Integer idConsultorio;
     private Integer numero;
     private String area;
     private Set citases = new HashSet(0);

    public Consultorios() {
    }

    public Consultorios(Integer numero, String area, Set citases) {
       this.numero = numero;
       this.area = area;
       this.citases = citases;
    }
   
    public Integer getIdConsultorio() {
        return this.idConsultorio;
    }
    
    public void setIdConsultorio(Integer idConsultorio) {
        this.idConsultorio = idConsultorio;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }




}


