package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidades generated by hbm2java
 */
public class Especialidades  implements java.io.Serializable {


     private Integer idEspecialidad;
     private String tipo;
     private Set medicoses = new HashSet(0);

    public Especialidades() {
    }

    public Especialidades(String tipo, Set medicoses) {
       this.tipo = tipo;
       this.medicoses = medicoses;
    }
   
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set medicoses) {
        this.medicoses = medicoses;
    }




}


