package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Farmacias generated by hbm2java
 */
public class Farmacias implements java.io.Serializable {

    private Integer idFarmacia;
    private String direccion;
    private Set clinicases = new HashSet(0);
    private Set medicamentoses = new HashSet(0);

    public Farmacias() {
    }

    public Farmacias(String direccion, Set clinicases, Set medicamentoses) {
        this.direccion = direccion;
        this.clinicases = clinicases;
        this.medicamentoses = medicamentoses;
    }

    public Integer getIdFarmacia() {
        return this.idFarmacia;
    }

    public void setIdFarmacia(Integer idFarmacia) {
        this.idFarmacia = idFarmacia;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Set getClinicases() {
        return this.clinicases;
    }

    public void setClinicases(Set clinicases) {
        this.clinicases = clinicases;
    }

    public Set getMedicamentoses() {
        return this.medicamentoses;
    }

    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }

}
