package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private Integer idMedico;
     private Especialidades especialidades;
     private String nombre;
     private String apellido;
     private String especialidad;
     private String telefono;
     private Set citases = new HashSet(0);

    public Medicos() {
    }

    public Medicos(Especialidades especialidades, String nombre, String apellido, String especialidad, String telefono, Set citases) {
       this.especialidades = especialidades;
       this.nombre = nombre;
       this.apellido = apellido;
       this.especialidad = especialidad;
       this.telefono = telefono;
       this.citases = citases;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public Especialidades getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Especialidades especialidades) {
        this.especialidades = especialidades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }




}


