package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private Integer idMedicamento;
     private Farmacias farmacias;
     private Proveedores proveedores;
     private String nombre;
     private String tipo;
     private Set pacienteses = new HashSet(0);

    public Medicamentos() {
    }

    public Medicamentos(Farmacias farmacias, Proveedores proveedores, String nombre, String tipo, Set pacienteses) {
       this.farmacias = farmacias;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.tipo = tipo;
       this.pacienteses = pacienteses;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public Farmacias getFarmacias() {
        return this.farmacias;
    }
    
    public void setFarmacias(Farmacias farmacias) {
        this.farmacias = farmacias;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }




}


