package persistencia;
// Generated 08-21-2018 10:52:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer idPaciente;
     private Clinicas clinicas;
     private Medicamentos medicamentos;
     private String nombre;
     private String apellido;
     private String sexo;
     private String fechaNacimiento;
     private String telefono;
     private String direccion;
     private Set citases = new HashSet(0);

    public Pacientes() {
    }

    public Pacientes(Clinicas clinicas, Medicamentos medicamentos, String nombre, String apellido, String sexo, String fechaNacimiento, String telefono, String direccion, Set citases) {
       this.clinicas = clinicas;
       this.medicamentos = medicamentos;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.citases = citases;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Clinicas getClinicas() {
        return this.clinicas;
    }
    
    public void setClinicas(Clinicas clinicas) {
        this.clinicas = clinicas;
    }
    public Medicamentos getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(Medicamentos medicamentos) {
        this.medicamentos = medicamentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }




}


